#pragma once
#include <iostream>
#include <vector>
#include <sstream>
#include <clocale>
#include  <conio.h>
#include <cstring> 
#include <iomanip>
#include <fstream>
#include <cstdlib>
#include <windows.h>
#include <unordered_map>
#include "Check.h"
#include "EnterValue.h"
#include "Pipe.h"